# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5111cf1a9119686a1226d941fb33a329623a83f6f2269fc5b468db01599fa3e85007eabf6694608f71a4881141717f18e246f30bab9bef3e189bbe89f0c9daf7

test:
  secret_key_base: e9078a5be3f5e6f2b396f5792b486f80fa75ed80435684ca33e9e5abe355a20006bc21eec104b52c8f18cc2d7e78382c9f0e9f34dd2f7ba388ea97a9decc9503

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
